// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "minimal-card": {
      name: "minimal-card",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/minimal-card")),
      source: "",
      files: ["registry/default/ui/minimal-card.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "three-d-carousel": {
      name: "three-d-carousel",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/three-d-carousel")),
      source: "",
      files: ["registry/default/ui/three-d-carousel.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "glass-button": {
      name: "glass-button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/glass-button")),
      source: "",
      files: ["registry/default/ui/glass-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "magical-button": {
      name: "magical-button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/magical-button")),
      source: "",
      files: ["registry/default/ui/magical-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "slide-button": {
      name: "slide-button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/slide-button")),
      source: "",
      files: ["registry/default/ui/slide-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "slider-button": {
      name: "slider-button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/slider-button")),
      source: "",
      files: ["registry/default/ui/slider-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "remove-button": {
      name: "remove-button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/remove-button")),
      source: "",
      files: ["registry/default/ui/remove-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "minimal-card-demo": {
      name: "minimal-card-demo",
      type: "components:example",
      registryDependencies: ["minimal-card"],
      component: React.lazy(() => import("@/registry/default/example/minimal-card-demo")),
      source: "",
      files: ["registry/default/example/minimal-card-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "three-d-carousel-demo": {
      name: "three-d-carousel-demo",
      type: "components:example",
      registryDependencies: ["three-d-carousel"],
      component: React.lazy(() => import("@/registry/default/example/three-d-carousel-demo")),
      source: "",
      files: ["registry/default/example/three-d-carousel-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "glass-button-demo": {
      name: "glass-button-demo",
      type: "components:example",
      registryDependencies: ["glass-button"],
      component: React.lazy(() => import("@/registry/default/example/glass-button-demo")),
      source: "",
      files: ["registry/default/example/glass-button-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "magical-button-demo": {
      name: "magical-button-demo",
      type: "components:example",
      registryDependencies: ["magical-button"],
      component: React.lazy(() => import("@/registry/default/example/magical-button-demo")),
      source: "",
      files: ["registry/default/example/magical-button-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "slide-button-demo": {
      name: "slide-button-demo",
      type: "components:example",
      registryDependencies: ["slide-button"],
      component: React.lazy(() => import("@/registry/default/example/slide-button-demo")),
      source: "",
      files: ["registry/default/example/slide-button-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "slider-button-demo": {
      name: "slider-button-demo",
      type: "components:example",
      registryDependencies: ["slider-button"],
      component: React.lazy(() => import("@/registry/default/example/slider-button-demo")),
      source: "",
      files: ["registry/default/example/slider-button-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "remove-button-demo": {
      name: "remove-button-demo",
      type: "components:example",
      registryDependencies: ["remove-button"],
      component: React.lazy(() => import("@/registry/default/example/remove-button-demo")),
      source: "",
      files: ["registry/default/example/remove-button-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
